//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group_Lib2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public book()
        {
            this.brrow_data = new HashSet<brrow_data>();
            this.return_record = new HashSet<return_record>();
        }
    
        public int bookid { get; set; }
        public Nullable<int> booktype { get; set; }
        public string bookauthor { get; set; }
        public string bookname { get; set; }
        public string bookImgSrc { get; set; }
        public string booklibrary { get; set; }
        public Nullable<System.DateTime> bookpubdate { get; set; }
    
        public virtual bookType bookType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<brrow_data> brrow_data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<return_record> return_record { get; set; }
    }
}
