//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group_Lib2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookManagerSystemEntities : DbContext
    {
        public BookManagerSystemEntities()
            : base("name=BookManagerSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<book> book { get; set; }
        public virtual DbSet<bookType> bookType { get; set; }
        public virtual DbSet<brrow_data> brrow_data { get; set; }
        public virtual DbSet<reader> reader { get; set; }
        public virtual DbSet<return_record> return_record { get; set; }
    }
}
